/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pack;

import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.JLabel;

/**
 *
 * @author jonatanLara
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    int x,y;
    
    public Panel() {
        initComponents();
       
    }
    public void puntoMouse(JLabel label){
        Point point = MouseInfo.getPointerInfo().getLocation();
        System.out.println(point);
        label.setLocation(point.x -x , point.y -y);
    }
    
    public void eventMouse(java.awt.event.MouseEvent evt){
       
        x=evt.getX();
        y=evt.getY();
        
    }
    public void win(){
      
      
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagenLeon = new javax.swing.JLabel();
        labelOso = new javax.swing.JLabel();
        Letra_L = new javax.swing.JLabel();
        letra_E = new javax.swing.JLabel();
        letra_O = new javax.swing.JLabel();
        letra_N = new javax.swing.JLabel();
        letra_S = new javax.swing.JLabel();
        letra_O_2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ImagenLeon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagenLeon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dibujodeleonparaimprimir5.png"))); // NOI18N

        labelOso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dibujos-animales.png"))); // NOI18N

        Letra_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/L.jpg"))); // NOI18N
        Letra_L.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Letra_LMouseDragged(evt);
            }
        });
        Letra_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Letra_LMousePressed(evt);
            }
        });

        letra_E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/E.gif"))); // NOI18N
        letra_E.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                letra_EMouseDragged(evt);
            }
        });
        letra_E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra_EMousePressed(evt);
            }
        });

        letra_O.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/O.jpg"))); // NOI18N
        letra_O.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                letra_OMouseDragged(evt);
            }
        });
        letra_O.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra_OMousePressed(evt);
            }
        });

        letra_N.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/n.jpg"))); // NOI18N
        letra_N.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                letra_NMouseDragged(evt);
            }
        });
        letra_N.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra_NMousePressed(evt);
            }
        });

        letra_S.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/s.jpg"))); // NOI18N
        letra_S.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                letra_SMouseDragged(evt);
            }
        });
        letra_S.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra_SMouseReleased(evt);
            }
        });

        letra_O_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/O.jpg"))); // NOI18N
        letra_O_2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                letra_O_2MouseDragged(evt);
            }
        });
        letra_O_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra_O_2MousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setText("Revisar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenLeon)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(labelOso))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(letra_S, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(letra_O, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(letra_N)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(letra_O_2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(letra_E)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Letra_L)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(305, 305, 305))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelOso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ImagenLeon)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(letra_N)
                            .addComponent(letra_O)
                            .addComponent(letra_O_2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letra_E)
                            .addComponent(Letra_L)
                            .addComponent(letra_S)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letra_OMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra_OMousePressed
        // TODO add your handling code here:
        this.eventMouse(evt);
    }//GEN-LAST:event_letra_OMousePressed

    private void letra_OMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra_OMouseDragged
        // TODO add your handling code here:
        this.puntoMouse(letra_O);
    }//GEN-LAST:event_letra_OMouseDragged

    private void Letra_LMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_LMousePressed
            this.eventMouse(evt);
    }//GEN-LAST:event_Letra_LMousePressed

    private void Letra_LMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_LMouseDragged
        // TODO add your handling code here:
        this.puntoMouse(Letra_L);
    }//GEN-LAST:event_Letra_LMouseDragged

    private void letra_EMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra_EMousePressed
        this.eventMouse(evt);
    }//GEN-LAST:event_letra_EMousePressed

    private void letra_EMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra_EMouseDragged
        this.puntoMouse(letra_E);
    }//GEN-LAST:event_letra_EMouseDragged

    private void letra_NMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra_NMousePressed
        this.eventMouse(evt);
    }//GEN-LAST:event_letra_NMousePressed

    private void letra_NMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra_NMouseDragged
        this.puntoMouse(letra_N);
    }//GEN-LAST:event_letra_NMouseDragged

    private void letra_SMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra_SMouseReleased
        this.eventMouse(evt);
    }//GEN-LAST:event_letra_SMouseReleased

    private void letra_SMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra_SMouseDragged
       this.puntoMouse(letra_S);
    }//GEN-LAST:event_letra_SMouseDragged

    private void letra_O_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra_O_2MousePressed
        this.eventMouse(evt);
    }//GEN-LAST:event_letra_O_2MousePressed

    private void letra_O_2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra_O_2MouseDragged
        this.puntoMouse(letra_O_2);
    }//GEN-LAST:event_letra_O_2MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        win();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenLeon;
    private javax.swing.JLabel Letra_L;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelOso;
    private javax.swing.JLabel letra_E;
    private javax.swing.JLabel letra_N;
    private javax.swing.JLabel letra_O;
    private javax.swing.JLabel letra_O_2;
    private javax.swing.JLabel letra_S;
    // End of variables declaration//GEN-END:variables
}
